dist: trusty
language: java
addons:
  firefox: 58.0.1
before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
    - mkdir webdrivers
    - tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C webdrivers
    - export PATH=$PATH:$PWD/webdrivers
    - geckodriver --version
    - whereis geckodriver
    - export MOZ_HEADLESS=1
script:
  - mvn verify -Dwebdriver="firefox" -Dwebdriver.headless="1"
