dist: trusty
language: java
addons:
  chrome: stable
  #firefox: latest
before_install:
    - # for chrome : start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
env:
      - # for firefox
      - #MOZ_HEADLESS=1

script:
  - mvn test