dist: trusty
language: java
addons:
  #firefox: 58.0.1
  chrome: stable
before_install:
    - # wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz
    - apt-get install unzip
    - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
    - mkdir webdrivers
    - #tar -xzf geckodriver-v0.19.1-linux64.tar.gz -C webdrivers
    - unzip chromedriver_linux64.zip -d webdrivers
    - export PATH=$PATH:$PWD/webdrivers
    - #geckodriver --version
    - chromedriver -version
    - #export MOZ_HEADLESS=1
script:
  - mvn verify -Dwebdriver="chrome" -Dwebdriver.headless="1"
